#Generated using get_name_to_code() in /dev/dev_functions.py
name_to_code = {'us dollars' : 'USD', '42 coin' : '42', '365coin' : '365', '404coin' : '404', 
				'sixeleven' : '611', '808' : '808', 'octocoin' : '888', '1337' : '1337', 
				'2015 coin' : '2015', 'bitcoin' : 'BTC', 'ethereum' : 'ETH', 'litecoin' : 'LTC', 
				'digitalcash' : 'DASH', 'monero' : 'XMR', 'nxt' : 'NXT', 'ethereum classic' : 'ETC', 
				'dogecoin' : 'DOGE', 'zcash' : 'ZEC', 'bitshares' : 'BTS', 'digibyte' : 'DGB', 
				'ripple' : 'XRP', 'bitcoindark' : 'BTCD', 'peercoin' : 'PPC', 'craigscoin' : 'CRAIG', 
				'bitstake' : 'XBS', 'paycoin' : 'XPY', 'prospercoin' : 'PRC', 'ybcoin' : 'YBC', 
				'darkkush' : 'DANK', 'givecoin' : 'GIVE', 'kobocoin' : 'KOBO', 'darktoken' : 'DT', 
				'cetus coin' : 'CETI', 'supcoin' : 'SUP', 'petrodollar' : 'XPD', 'geocoin' : 'GEO', 
				'cleverhash' : 'CHASH', 'spreadcoin' : 'SPR', 'nxti' : 'NXTI', 'insanity coin' : 'WOLF', 
				'dogeparty' : 'XDP', 'asia coin' : 'AC', 'acoin' : 'ACOIN', 'aero coin' : 'AERO', 
				'alphacoin' : 'ALF', 'aegis' : 'AGS', 'americancoin' : 'AMC', 'aliencoin' : 'ALN', 
				'apexcoin' : 'APEX', 'archcoin' : 'ARCH', 'argentum' : 'ARG', 'aricoin' : 'ARI', 
				'aurora coin' : 'AUR', 'axron' : 'AXR', 'battlecoin' : 'BCX', 'benjamins' : 'BEN', 
				'betacoin' : 'BET', 'bitbean' : 'BITB', 'bluecoin' : 'BLU', 'blackcoin' : 'BLK', 
				'boostcoin' : 'BOST', 'bqcoin' : 'BQC', 'myriadcoin' : 'XMY', 'mooncoin' : 'MOON', 
				'zetacoin' : 'ZET', 'sexcoin' : 'SXC', 'quatloo' : 'QTL', 'energycoin' : 'ENRG', 
				'quarkcoin' : 'QRK', 'riecoin' : 'RIC', 'digicoin' : 'DGC', 'limecoinx' : 'LIMX', 
				'bitbar' : 'BTB', 'caix' : 'CAIX', 'bytecoin' : 'BTE', 'bitgem' : 'BTG*', 
				'bitmark' : 'BTM', 'cryptobuk' : 'BUK', 'cachecoin' : 'CACH', 'bottlecaps' : 'CAP', 
				'cashcoin' : 'CASH', 'cryptobullion' : 'CBX', 'cannacoin' : 'CCN', 'cindercoin' : 'CIN', 
				'cinnicoin' : 'CINNI', 'checkcoin' : 'CXC', 'clams' : 'CLAM', 'cloakcoin' : 'CLOAK', 
				'copperlark' : 'CLR', 'cosmoscoin' : 'CMC', 'chinacoin' : 'CNC', 'concealcoin' : 'CNL', 
				'community coin' : 'COMM', 'coolcoin' : 'COOL', 'crackcoin' : 'CRACK', 'craftcoin' : 'CRC', 
				'cryptcoin' : 'CRYPT', 'casinocoin' : 'CSC', 'emark' : 'DEM', 'diamond' : 'DMD', 
				'darkcash' : 'DRKC', 'darkshibe' : 'DSB', 'devcoin' : 'DVC', 'earthcoin' : 'EAC', 
				'e-gulden' : 'EFL', 'elacoin' : 'ELC', 'einsteinium' : 'EMC2', 'emerald' : 'EMD', 
				'exclusive coin' : 'EXCL', 'execoin' : 'EXE', 'ezcoin' : 'EZC', 'flappy coin' : 'FLAP', 
				'fuel2coin' : 'FC2', 'fireflycoin' : 'FFC', 'fibre' : 'FIBRE', 'fireroostercoin' : 'FRC', 
				'fluttercoin' : 'FLT', 'franko' : 'FRK', 'fractalcoin' : 'FRAC', 'feathercoin' : 'FTC', 
				'grandcoin' : 'GDC', 'globalcoin' : 'GLC', 'goldcoin' : 'GLD', 'galaxycoin' : 'GLX', 
				'glyphcoin' : 'GLYPH', 'gameleaguecoin' : 'GML', 'guerillacoin' : 'GUE', 'halcyon' : 'HAL', 
				'hobonickels' : 'HBN', 'huntercoin' : 'HUC', 'heavycoin' : 'HVC', 'hyperstake' : 'HYP', 
				'icebergcoin' : 'ICB', 'infinite coin' : 'IFC', 'iocoin' : 'IOC', 'ixcoin' : 'IXC', 
				'jumbucks coin' : 'JBS', 'junkcoin' : 'JKC', 'judgecoin' : 'JUDGE', 'klondike coin' : 'KDC', 
				'keycoin' : 'KEY*', 'krugercoin' : 'KGC', 'coinworkscoin' : 'LAB*', 'legendary coin' : 'LGD*', 
				'lucky7coin' : 'LK7', 'luckycoin' : 'LKY', 'lightspeedcoin' : 'LSD', 'litebar ' : 'LTB', 
				'litecoindark' : 'LTCD', 'litecoinx' : 'LTCX', 'librexcoin' : 'LXC', 'lycancoin' : 'LYC', 
				'maxcoin' : 'MAX', 'megacoin' : 'MEC', 'mediterraneancoin' : 'MED', 'minerals coin' : 'MIN', 
				'mintcoin' : 'MINT', 'cryptsy mining contract' : 'MN', 'mincoin' : 'MNC', 'murraycoin' : 'MRY', 
				'mysterycoin' : 'MYST*', 'mazacoin' : 'MZC', 'nanotoken' : 'NAN', 'nautilus coin' : 'NAUT', 
				'navcoin' : 'NAV', 'nybble' : 'NBL', 'neocoin' : 'NEC', 'netcoin' : 'NET', 
				'nimbus coin' : 'NMB', 'noirbits' : 'NRB', 'noblecoin' : 'NOBL', 'noirshares' : 'NRS', 
				'novacoin' : 'NVC', 'namecoin' : 'NMC', 'nyancoin' : 'NYAN', 'opalcoin' : 'OPAL', 
				'orbitcoin' : 'ORB', 'opensourcecoin' : 'OSC', 'philosophersstone' : 'PHS', 'cryptsy points' : 'POINTS', 
				'potcoin' : 'POT', 'pseudocash' : 'PSEUD', 'protoshares' : 'PTS*', 'phoenixcoin' : 'PXC', 
				'reddcoin' : 'RDD', 'ripoffcoin' : 'RIPO', 'ronpaulcoin' : 'RPC', 'rotocoin' : 'RT2', 
				'royalcoin' : 'RYC', 'razorcoin' : 'RZR', 'saturn2coin' : 'SAT2', 'stablecoin' : 'SBC', 
				'shadowcash' : 'SDC', 'saffroncoin' : 'SFR', 'shadecoin' : 'SHADE', 'shieldcoin' : 'SHLD', 
				'silkcoin' : 'SILK', 'sterlingcoin' : 'SLG', 'smartcoin' : 'SMC', 'solecoin' : 'SOLE', 
				'spaincoin' : 'SPA', 'spots' : 'SPT', 'securecoin' : 'SRC', 'ssvcoin' : 'SSV', 
				'stellar' : 'XLM', 'supercoin' : 'SUPER', 'bitswift' : 'SWIFT', 'synccoin' : 'SYNC', 
				'syscoin' : 'SYS', 'tagcoin' : 'TAG', 'takcoin' : 'TAK', 'teslacoin' : 'TES', 
				'tigercoin' : 'TGC', 'titcoin' : 'TIT', 'torcoin' : 'TOR', 'terracoin' : 'TRC', 
				'tittiecoin' : 'TTC', 'umbrella' : 'ULTC', 'unbreakablecoin' : 'UNB', 'unobtanium' : 'UNO', 
				'urocoin' : 'URO', 'unitarystatus dollar' : 'USDE', 'ultracoin' : 'UTC', 'utility coin' : 'UTIL', 
				'vidiocoin' : 'VDO', 'viacoin' : 'VIA', 'vootcoin' : 'VOOT', 'vericoin' : 'VRC', 
				'whitecoin' : 'WC', 'worldcoin' : 'WDC', 'sapiencecoin' : 'XAI', 'socialxbotcoin' : 'XBOT', 
				'x11 coin' : 'XC', 'xcash' : 'XCASH', 'crypti' : 'XCR', 'joulecoin' : 'XJO', 
				'libertycoin' : 'XLB', 'primecoin' : 'XPM', 'stealthcoin' : 'XST', 'xxxcoin' : 'XXX', 
				'yaccoin' : 'YAC', 'zcc coin' : 'ZCC', 'zedcoins' : 'ZED', 'ziftrcoin' : 'ZRC*', 
				'elektron' : 'EKN', 'xaucoin' : 'XAU', 'timescoin' : 'TMC', 'nem' : 'XEM', 
				'burstcoin' : 'BURST', 'nubits' : 'NBT', 'storjcoin' : 'SJCX', 'startcoin' : 'START', 
				'bigcoin' : 'HUGE', 'counterparty' : 'XCP', 'maidsafe coin' : 'MAID', '007 coin' : '007', 
				'nushares' : 'NSR', 'monacoin' : 'MONA', 'solarfarm' : 'CELL', 'tekcoin' : 'TEK', 
				'positron' : 'TRON', 'bitbay' : 'BAY', 'neutron' : 'NTRN', 'sling coin' : 'SLING', 
				'vcash' : 'XVC', 'cravecoin' : 'CRAVE', 'blocknet' : 'BLOCK', 'stability shares' : 'XSI', 
				'giga hash' : 'GHS', 'bytecent' : 'BYC', 'gridcoin' : 'GRC', 'gemz social' : 'GEMZ', 
				'kryptcoin' : 'KTK', 'horizon' : 'HZ', 'faircoin' : 'FAIR', 'qoracoin' : 'QORA', 
				'gulden' : 'NLG', 'rubycoin' : 'RBY', 'pesetacoin' : 'PTC', 'kore' : 'KORE', 
				'wild beast coin' : 'WBB', 'sonic screw driver coin' : 'SSD', 'tilecoin' : 'XTC', 'dnotes' : 'NOTE', 
				'gridpay' : 'GRID*', 'florincoin' : 'FLO', 'maieuticoin' : 'MMXIV', '8bit coin' : '8BIT', 
				'sativa coin' : 'STV', 'ebolashare' : 'EBS', 'aerome' : 'AM', 'coin magi' : 'XMG', 
				'ambercoin' : 'AMBER', 'jackpotcoin' : 'JPC', 'nakomotodark' : 'NKT', 'joincoin' : 'J', 
				'ghostcoin' : 'GHC', 'daytrader coin' : 'DTC', 'artbyte' : 'ABY', 'litedoge' : 'LDOGE', 
				'mastertradercoin' : 'MTR', 'triangles coin' : 'TRI', 'swarmcoin' : 'SWARM', 'boolberry' : 'BBR', 
				'bitcrystal' : 'BTCRY', 'bitcredit' : 'BCR', 'pebble coin' : 'XPB', 'dirac coin' : 'XDQ', 
				'folding coin' : 'FLDC', 'solarcoin' : 'SLR', 'social media coin' : 'SMAC', 'truckcoin' : 'TRK', 
				'ucoin' : 'U', 'unitus' : 'UIS', 'cypherpunkcoin' : 'CYP', 'ufo coin' : 'UFO', 
				'ascension coin' : 'ASN', 'orangecoin' : 'OC', 'gsm coin' : 'GSM', 'friendshipcoin' : 'FSC2', 
				'nxtty' : 'NXTTY', 'qubuck coin' : 'QBK', 'blakecoin' : 'BLC', 'maryjane coin' : 'MARYJ', 
				'omnicron' : 'OMC', 'gigcoin' : 'GIG', 'cybercoin' : 'CC', 'bitstarcoin' : 'BITS', 
				'ltbcoin' : 'LTBC', 'neoscoin' : 'NEOS', 'hypercoin' : 'HYPER', 'vtorrent' : 'VTR', 
				'metalcoin' : 'METAL', 'pinkcoin' : 'PINK', 'greencoin' : 'GRE', 'xg sports' : 'XG', 
				'childcoin' : 'CHILD', 'boom coin' : 'BOOM', 'instamine nuggets' : 'MINE', 'ros coin' : 'ROS', 
				'unattanium' : 'UNAT', 'slimcoin' : 'SLM', 'gaia platform' : 'GAIA', 'trustplus' : 'TRUST', 
				'fantomcoin ' : 'FCN', 'cryptonite' : 'XCN', 'curecoin' : 'CURE', 'gridmaster' : 'GMC', 
				'memorycoin' : 'MMC', 'bitcoinplus' : 'XBC', 'conspiracy coin ' : 'CYC', 'mastercoin' : 'MSC', 
				'eggcoin' : 'EGG', 'coin.2' : 'C2', 'glowshares' : 'GSX', 'camcoin' : 'CAM', 
				'ribbit rewards' : 'RBR', 'quotient' : 'XQN', 'icash' : 'ICASH', 'node' : 'NODE', 
				'sooncoin' : 'SOON', 'bitmiles' : 'BTMI', 'event token' : 'EVENT', '1credit' : '1CR', 
				'viorcoin' : 'VIOR', 'xcoin' : 'XCO', 'virtualmining coin' : 'VMC', 'marscoin' : 'MRS', 
				'viral coin' : 'VIRAL', 'equilibrium coin' : 'EQM', 'islacoin' : 'ISL', 'quicksilver coin' : 'QSLV', 
				'world trade funds' : 'XWT', 'deoxyribose' : 'XNA', 'radonpay' : 'RDN', 'skullbuzz' : 'SKB', 
				'globalboost' : 'BSTY', 'cryptofocus' : 'FCS', 'gambit coin' : 'GAM', 'nexus' : 'NXS', 
				'crypto escudo' : 'CESC', 'twelve coin' : 'TWLV', 'eagscoin' : 'EAGS', 'multiwallet coin' : 'MWC', 
				'audiocoin' : 'ADC', 'marscoin ' : 'MARS', 'megastake' : 'XMS', 'sphere coin' : 'SPHR', 
				'singular' : 'SIGU', 'bitcointx' : 'BTX*', 'darkcrave' : 'DCC', 'supplyshock' : 'M1', 
				'darkbit' : 'DB', 'crypto' : 'CTO', 'edgecoin' : 'EDGE', 'bitlux' : 'LUX*', 
				'futcoin' : 'FUTC', 'global' : 'GLOBE', 'tamagucci' : 'TAM', 'morpheuscoin' : 'MRP', 
				'creva coin' : 'CREVA', 'forever coin' : 'XFC', 'bananabits' : 'NANAS', 'wood coin' : 'LOG', 
				'cerium' : 'XCE', 'anarchists prime' : 'ACP', 'droidz' : 'DRZ', 'gorillabucks' : 'BUCKS*', 
				'bowscoin' : 'BSC', 'darktron' : 'DRKT', 'cryptocircuits' : 'CIRC', 'incakoin' : 'NKA', 
				'versa token' : 'VERSA', 'empyrean' : 'EPY', 'squall coin' : 'SQL', 'polybit' : 'POLY', 
				'piggy coin' : 'PIGGY', 'charity coin' : 'CHA', 'milllionaire coin' : 'MIL', 'crown coin' : 'CRW', 
				'genstake' : 'GEN', 'pharmacoin' : 'XPH', 'quartz' : 'QTZ', 'arbit coin' : 'ARB', 
				'litestar coin' : 'LTS', 'spincoin' : 'SPC', 'goldpieces' : 'GP', 'bitz coin' : 'BITZ', 
				'dubcoin' : 'DUB', 'graviton' : 'GRAV', 'bob coin' : 'BOB', 'monetaverde' : 'MCN', 
				'quazar coin' : 'QCN', 'hedgecoin' : 'HEDG', 'song coin' : 'SONG', 'bitseeds' : 'XSEED', 
				'credits' : 'CRE', 'axiom coin' : 'AXIOM', 'smileycoin' : 'SMLY', 'rimbit' : 'RBT', 
				'chip' : 'CHIP', 'speccoin' : 'SPEC', 'gram coin' : 'GRAM', 'uncoin' : 'UNC', 
				'sprouts' : 'SPRTS', 'bitzeny' : 'ZNY', 'bitquark' : 'BTQ', 'parkbyte' : 'PKB', 
				'starcoin' : 'STR*', 'synergy' : 'SNRG', 'ghoul coin' : 'GHOUL', 'hellenic coin' : 'HNC', 
				'diggits' : 'DIGS', 'expanse' : 'EXP', 'global currency reserve' : 'GCR', 'mapcoin' : 'MAPC', 
				'xiaomicoin' : 'MI', 'paycon' : 'CON_', 'neucoin' : 'NEU*', 'transfer' : 'TX', 
				'groestlcoin ' : 'GRS', 'siacoin' : 'SC', 'clevercoin' : 'CLV', 'factoids' : 'FCT', 
				'lyrabar' : 'LYB', 'bitstone' : 'BST', 'prime-x1' : 'PXI', 'capricoin' : 'CPC', 
				'amsterdam coin' : 'AMS', 'obits coin' : 'OBITS', ' clubcoin' : 'CLUB', 'radium' : 'RADS', 
				'blitzcoin' : 'BLITZ', 'bithire' : 'HIRE*', 'evergreencoin' : 'EGC', 'mindcoin' : 'MND', 
				'i0coin' : 'I0C', 'bata' : 'BTA', 'karmacoin' : 'KARM', 'decred' : 'DCR', 
				'nas2coin' : 'NAS2', 'pakcoin' : 'PAK', 'creditbit ' : 'CRB', 'dogecoindark' : 'DOGED', 
				'augur' : 'REP', 'okcash' : 'OK', 'voxels' : 'VOX', 'synereo' : 'AMP', 
				'hodlcoin' : 'HODL', 'digix dao' : 'DGD', 'lisk' : 'LSK', 'waves' : 'WAVES', 
				'hitcoin' : 'HTC', 'gamecredits' : 'GAME', 'dashcoin' : 'DSH', 'dubaicoin' : 'DBIC', 
				'hicoin' : 'XHI', 'bioscrypto' : 'BIOS', 'khancoin' : 'KNC*', 'cabbageunit' : 'CAB', 
				'carpediemcoin' : 'DIEM', 'gamebetcoin' : 'GBT', 'sarcoin' : 'SAR', 'redcrowcoin' : 'RCX', 
				'powercoin' : 'PWR', 'trumpcoin' : 'TRUMP', 'prismchain' : 'PRM', 'bitcrystals' : 'BCY', 
				'rubies' : 'RBIES', 'steem' : 'STEEM', 'billarycoin' : 'BLRY', 'dotcoin' : 'DOT', 
				'scotcoin' : 'SCOT', 'darknet' : 'DNET', 'bitalphacoin' : 'BAC', 'international diamond coin' : 'XID*', 
				'grantcoin' : 'GRT', 'thecreed' : 'TCR', 'postcoin' : 'POST', 'influxcoin' : 'INFX', 
				'ethereumscrypt' : 'ETHS', 'phalanx' : 'PXL', 'numberscoin' : 'NUM', 'soulcoin' : 'SOUL', 
				'ionomy' : 'ION', 'growncoin' : 'GROW', 'supernet' : 'UNITY', 'oldsafecoin' : 'OLDSF', 
				'sunshotcoin' : 'SSTC', 'networkcoin' : 'NETC', 'gpu coin' : 'GPU', 'think and get rich coin' : 'TAGR', 
				'hempcoin' : 'HMP', 'adzcoin' : 'ADZ', 'gapcoin' : 'GAP', 'mayacoin' : 'MYC', 
				'invisiblecoin' : 'IVZ', 'virtacoin' : 'VTA', 'soilcoin' : 'SOIL', 'digicube' : 'CUBE', 
				'yocoin' : 'YOC', 'coin' : 'COIN*', 'vaperscoin' : 'VPRC', 'alpacoin' : 'APC', 
				'steps' : 'STEPS', 'debitcoin' : 'DBTC', 'universal currency' : 'UNIT', 'aeoncoin' : 'AEON', 
				'moincoin' : 'MOIN', 'sibcoin' : 'SIB', 'europecoin' : 'ERC', 'advancedinternetblock' : 'AIB', 
				'primechain' : 'PRIME', 'berncash' : 'BERN', 'bigup' : 'BIGUP', 'krypton' : 'KR', 
				'revolvercoin' : 'XRE', 'dragonsphere' : 'XDB', 'anti bitcoin' : 'ANTI', 'breakoutcoin' : 'BRK', 
				'colossuscoinxt' : 'COLX', 'mineum' : 'MNM', 'asiadigicoin' : 'ADCN', 'zeitcoin' : 'ZEIT', 
				'2givecoin' : '2GIVE', 'cryptographic anomaly' : 'CGA', 'swingcoin' : 'SWING', 'safeexchangecoin' : 'SAFEX', 
				'nebuchadnezzar' : 'NEBU', 'acescoin' : 'AEC', 'francs' : 'FRN', 'aiden' : 'ADN', 
				'pulse' : 'PULSE', 'number7' : 'N7', 'cygnus' : 'CYG', 'lgbtqoin' : 'LGBTQ', 
				'uther' : 'UTH', 'mediumproject' : 'MPRO', 'katzcoin' : 'KAT', 'supreme' : 'SPM', 
				'mojocoin' : 'MOJO', 'belacoin' : 'BELA', 'flash' : 'FLX', 'bolivarcoin' : 'BOLI', 
				'cludcoin' : 'CLUD', 'dimecoin' : 'DIME', 'flycoin' : 'FLY', 'high voltage coin' : 'HVCO', 
				'gizmocoin' : 'GIZ', 'grexitcoin' : 'GREXIT', 'carboncoin' : 'CARBON', 'digieuro' : 'DEUR', 
				'turron' : 'TUR', 'lemoncoin' : 'LEMON', 'stresscoin' : 'STS', 'dark lisk' : 'DISK', 
				'nevacoin' : 'NEVA', 'cryptokenz' : 'CYT', 'fuzzballs' : 'FUZZ', 'nukecoinz' : 'NKC', 
				'secretcoin' : 'SCRT', 'ratecoin' : 'XRA', 'xanaxcoin' : 'XNX', 'stakerush' : 'STHR', 
				'digital bullion gold' : 'DBG', 'bonescoin' : 'BON*', 'wmcoin' : 'WMC', 'gothiccoin' : 'GOTX', 
				'shrekcoin' : 'SHREK', 'stakers' : 'STA*', 'rise' : 'RISE', 'revenu' : 'REV', 
				'pabyosicoin' : 'PBC', 'obscurebay' : 'OBS', 'exitcoin' : 'EXIT', 'educoinv' : 'EDC', 
				'clinton' : 'CLINT', 'clockcoin' : 'CKC', 'vip tokens' : 'VIP', 'nxecoin' : 'NXE', 
				'zoomcoin' : 'ZOOM', 'dt token' : 'DRACO', 'yobitvirtualcoin' : 'YOVI', 'orlycoin' : 'ORLY', 
				'kuboscoin' : 'KUBO', 'inceptioncoin' : 'INCP', 'sharkcoin' : 'SAK', 'evilcoin' : 'EVIL', 
				'omegacoin' : 'OMA', 'monetaryunit' : 'MUE', 'cobracoin' : 'COX', 'bancor network token' : 'BNT', 
				'ekocoin' : 'EKO', 'bitsend' : 'BSD', 'destiny' : 'DES', '16bitcoin' : 'BIT16', 
				'project decorum' : 'PDC', 'cometcoin' : 'CMT', 'chesscoin' : 'CHESS', 'spacecoin' : 'SPACE', 
				'reecoin' : 'REE', 'liquid' : 'LQD', 'marvelous' : 'MARV', 'xde ii' : 'XDE2', 
				'vectorcoin 2.0 ' : 'VEC2', 'omni' : 'OMNI', 'genesyscoin' : 'GSY', 'trolltokens' : 'TKN*', 
				'let it ride' : 'LIR', 'mmnxt ' : 'MMNXT', 'scryptcoin' : 'SCRPT', 'lbry credits' : 'LBC', 
				'specie' : 'SPX', 'steem backed dollars' : 'SBD', 'cryptojacks' : 'CJ', 'putincoin' : 'PUT', 
				'kraken' : 'KRAK', 'dlisk' : 'DLISK', 'ibankcoin' : 'IBANK', 'stratis' : 'STRAT', 
				'voyacoin' : 'VOYA', 'entercoin (enter)' : 'ENTER', 'world gold coin' : 'WGC', 'bitmoon' : 'BM', 
				'frankywillcoin' : 'FRWC', 'psilocybin' : 'PSY', 'extremecoin' : 'XT', 'rustcoin' : 'RUST', 
				'newzealandcoin' : 'NZC', 'singulardtv' : 'SNGLS', 'xaurum' : 'XAUR', 'bitfinex tokens' : 'BFX', 
				'uniqredit' : 'UNIQ', 'chronoscoin' : 'CRX', 'decent' : 'DCT', 'pokechain' : 'XPOKE', 
				'mudracoin' : 'MUDRA', 'warpcoin' : 'WARP', 'coinomat' : 'CNMT', 'pizzacoin' : 'PIZZA', 
				'lutetium coin' : 'LC', 'heat ledger' : 'HEAT', 'iconomi' : 'ICN', 'exabyte (exb)' : 'EXB', 
				'wings dao' : 'WINGS', 'cryptodex' : 'CDX', 'returnbit' : 'RBIT', 'declouds' : 'DCS', 
				'komodo' : 'KMD', 'goldblocks' : 'GB', 'neo' : 'NEO', 'anoncoin' : 'ANC', 
				'syndicate' : 'SYNX', 'mass coin' : 'MC', 'e-dinar coin' : 'EDR', 'jewels' : 'JWL', 
				'waycoin' : 'WAY', 'mollycoin' : 'TAB', 'trigger' : 'TRIG', 'bitcny' : 'BITCNY', 
				'bitusd' : 'BITUSD', 'autumncoin' : 'ATM', 'save the ocean' : 'STO', 'sense' : 'SNS', 
				'fusion' : 'FSN', 'cartercoin' : 'CTC', 'totcoin' : 'TOT', 'bitcloud' : 'BTD', 
				'arkdao' : 'BOTS', 'mediccoin' : 'MDC', 'futurepoints' : 'FTP', 'zeta2coin' : 'ZET2', 
				'covencoin' : 'COV*', 'tellurion' : 'TELL', 'enecoin' : 'ENE', 'tdfb' : 'TDFB', 
				'blockpay' : 'BLOCKPAY', 'bittokens' : 'BXT', 'zayedcoin' : 'ZYD', 'mustangcoin' : 'MST', 
				'goonies' : 'GOON', 'veltor' : 'VLT', 'zonecoin' : 'ZNE', 'dickcoin' : 'DCK', 
				'circuits of value' : 'COVAL', 'darkgold' : 'DGDC', 'todaycoin' : 'TODAY', 'verium' : 'VRM', 
				'rootcoin' : 'ROOT', 'firstblood' : '1ST', 'gold pressed latinum' : 'GPL', 'dopecoin' : 'DOPE', 
				'b3 coin' : 'B3', 'fcoin' : 'FX', 'pioneershares' : 'PIO', 'gaycoin' : 'GAY', 
				'samsara coin' : 'SMSR', 'ubiqoin' : 'UBIQ', 'armory coin' : 'ARM', 'ringcoin' : 'RING', 
				'erbcoin' : 'ERB', 'lazarus' : 'LAZ', 'fonziecoin' : 'FONZ', 'bitcurrency' : 'BTCR', 
				'faucetcoin' : 'DROP', 'save and gain' : 'SANDG', 'steampunk' : 'PNK', 'dark moon' : 'MOOND', 
				'dollarcoin' : 'DLC', 'sentaro' : 'SEN', 'swiscoin' : 'SCN', 'wexcoin' : 'WEX', 
				'lathaan' : 'LTH', 'bitbronze' : 'BRONZ', 'shilling' : 'SH', 'mind gene' : 'MG', 
				'psicoin' : 'PSI', 'opair' : 'XPO', 'nolimitcoin' : 'NLC', 'pesobit' : 'PSB', 
				'beats' : 'XBTS', 'fitcoin' : 'FIT', 'panthercoin' : 'PINKX', 'firecoin' : 'FIRE', 
				'unfed coin' : 'UNF', 'sportscoin' : 'SPORT', 'peerplays' : 'PPY', 'nineeleventruthcoin' : 'NTC', 
				'egocoin' : 'EGO', 'bitluckcoin' : 'BTCL*', 'rcoin' : 'RCN*', 'x2coin' : 'X2', 
				'mycelium token' : 'MT', 'tianhe' : 'TIA', 'gbr coin' : 'GBRC', 'upcoin' : 'XUP', 
				'halloween coin' : 'HALLO', 'baseballcardcoin' : 'BBCC', 'emiratesgoldcoin' : 'EMIGR', 'bighancoin' : 'BHC', 
				'invictus' : 'INV', 'olympcoin' : 'OLYMP', 'delightpay' : 'DPAY', 'atomic coin' : 'ATOM', 
				'hacker gold' : 'HKG', 'antilitecoin' : 'ANTC', 'jobscoin' : 'JOBS', 'dogegorecoin' : 'DGORE', 
				'the hempcoin' : 'THC', 'tetra' : 'TRA', 'resumeo shares' : 'RMS', 'fujicoin' : 'FJC', 
				'vaporcoin' : 'VAPOR', 'sydpakcoin' : 'SDP', 'recovery right tokens' : 'RRT', 'zcoin' : 'XZC', 
				'premium' : 'PRE', 'caliphcoin' : 'CALC', 'leacoin' : 'LEA', 'californium' : 'CF', 
				'crankcoin' : 'CRNK', 'coffeecoin' : 'CFC', 'victoriouscoin' : 'VTY', 'safecoin' : 'SFE', 
				'ardor' : 'ARDR', 'blackshadowcoin' : 'BS', 'jiffycoin' : 'JIF', 'crabcoin' : 'CRAB', 
				'aircoin' : 'AIR*', 'president clinton' : 'HILL', 'forexcoin' : 'FOREX', 'moneta' : 'MONETA', 
				'eclipse' : 'EC', 'rublebit' : 'RUBIT', 'happycreatorcoin ' : 'HCC', 'braincoin' : 'BRAIN', 
				'vertex' : 'VTX', 'krcoin' : 'KRC', 'biglifecoin' : 'LFC', 'zurcoin' : 'ZUR', 
				'nubiscoin' : 'NUBIS', 'tennet' : 'TENNET', 'peacecoin' : 'PEC', 'goldmaxcoin' : 'GMX', 
				'32bitcoin' : '32BIT', 'ganjacoin v2' : 'GNJ', 'teamup' : 'TEAM', 'scrypttoken' : 'SCT', 
				'lanacoin' : 'LANA', 'elementrem' : 'ELE', 'guccionecoin' : 'GCC', 'andromedacoin' : 'AND', 
				'byteball' : 'GBYTE', 'equalcoin' : 'EQUAL', 'sweetstake' : 'SWEET', '2bacco coin' : '2BACCO', 
				'darkknightcoin' : 'DKC', 'choofcoin' : 'CHOOF', 'cashout' : 'CSH', 'zclassic' : 'ZCL', 
				'royalcoin 2.0' : 'RYCN', 'pabyosi coin' : 'PCS', 'netbit' : 'NBIT', 'winecoin' : 'WINE', 
				'darcrus' : 'DAR', 'ark' : 'ARK', 'inflationcoin' : 'IFLT', 'zcashdarkcoin' : 'ZECD', 
				'zcrypt' : 'ZXT', 'washingtoncoin' : 'WASH', 'teslacoilcoin' : 'TESLA', 'luckyblocks (lucky)' : 'LUCKY', 
				'vslice' : 'VSL', 'troll payment' : 'TPG', 'leocoin' : 'LEO', 'midnight ' : 'MDT', 
				'cbd crystals' : 'CBD', 'posex' : 'PEX', 'insanecoin' : 'INSANE', 'golem network token' : 'GNT', 
				'pencoin' : 'PEN', 'luckchain' : 'BASH', 'famecoin' : 'FAME', 'liviacoin' : 'LIV', 
				'sex pistols' : 'SP', 'megaflash' : 'MEGA', 'veros' : 'VRS', 'arab league coin' : 'ALC', 
				'etherdoge' : 'DOGETH', 'kilocoin' : 'KLC', 'hush' : 'HUSH', 'dream8coin' : 'DRM8', 
				'fistbump' : 'FIST', 'ebitz' : 'EBZ', 'digital rupees' : 'DRS', 'free game zone' : 'FGZ', 
				'bosoncoin' : 'BOSON', 'artexcoin' : 'ATX', 'platiniumcoin' : 'PNC', 'bearddollars' : 'BRDD', 
				'time' : 'TIME', 'bipcoin' : 'BIP', 'xencoin' : 'XNC', 'embercoin' : 'EMB', 
				'coin to the future' : 'BTTF', 'dollaronline' : 'DLR', 'cosmic' : 'CSMIC', 'firstcoin' : 'FIRST', 
				'spacecash' : 'SCASH', 'xenixcoin' : 'XEN', 'jio token' : 'JIO', 'iwallet' : 'IW', 
				'janus' : 'JNS', 'trickycoin' : 'TRICK', 'deltacredits' : 'DCRE', 'freecoin' : 'FRE', 
				'npccoin' : 'NPC', 'plncoin' : 'PLNC', 'digigems' : 'DGMS', 'icobid' : 'ICOB', 
				'aquariuscoin' : 'ARCO', 'kurrent' : 'KURT', 'creatio' : 'XCRE', 'eternity' : 'ENT', 
				'ur' : 'UR', 'metal music v3' : 'MTLM3', 'old dogs new tricks' : 'ODNT', 'eurocoin' : 'EUC', 
				'cooldarkcoin' : 'CCX', 'bitcoinfast' : 'BCF', 'seedshares' : 'SEEDS', 'poswallet' : 'POSW', 
				'tokes' : 'TKS', 'bitconnect coin' : 'BCCOIN', 'shortycoin' : 'SHORTY', 'procom' : 'PCM', 
				'kernalcoin' : 'KC', 'coralpay' : 'CORAL', 'bam' : 'BAM', 'nexium' : 'NXC', 
				'moneycoin' : 'MONEY', 'blackstar' : 'BSTAR', 'horse power' : 'HSP', 'hazmatcoin' : 'HZT', 
				'cryptospots' : 'CS', 'poolstamp' : 'XSP', 'cryptocarbon' : 'CCRB', 'bullshitcoin' : 'BULLS', 
				'incent' : 'INCNT', 'iconic' : 'ICON', 'newinvestcoin' : 'NIC', 'avoncoin' : 'ACN', 
				'enigma' : 'XNG', 'cannabis industry coin' : 'XCI', 'lookcoin' : 'LOOK', 'loco' : 'LOC', 
				'mmxvi' : 'MMXVI', 'trustcoin' : 'TRST', 'miscoin' : 'MIS', 'worldpay' : 'WOP', 
				'conquestcoin' : 'CQST', 'impulse coin' : 'IMPS', 'incoin' : 'IN', 'thechiefcoin' : 'CHIEF', 
				'goat' : 'GOAT', 'analcoin' : 'ANAL', 'russiacoin' : 'RC', 'pandacoin' : 'PND', 
				'pxcoin' : 'PX', 'canada ecoin' : 'CND*', 'optioncoin' : 'OPTION', 'avatar coin' : 'AV', 
				'limited coin' : 'LTD', 'gameunits' : 'UNITS', 'heelcoin' : 'HEEL', 'gakhcoin' : 'GAKH', 
				'shift' : 'SHIFT', 's88 coin' : 'S8C', 'leverage coin' : 'LVG', 'draculacoin' : 'DRA', 
				'allsafe' : 'ASAFE2', 'litecreed' : 'LTCR', 'quebecoin' : 'QBC', 'procoin' : 'XPRO', 
				'astral' : 'AST*', 'giftnet' : 'GIFT', 'purevidz' : 'VIDZ', 'incrementum' : 'INC', 
				'pentacoin' : 'PTA', 'acidcoin' : 'ACID', 'zlitequbit' : 'ZLQ', 'radicalcoin' : 'RADI', 
				'returncoin' : 'RNC', 'golos' : 'GOLOS', 'pascal coin' : 'PASC', 'twistercoin' : 'TWIST', 
				'paypeer' : 'PAYP', 'darkether' : 'DETH', 'yaycoin' : 'YAY', 'yescoin' : 'YES', 
				'lenincoin' : 'LENIN', 'mrsacoin' : 'MRSA', 'osmiumcoin' : 'OS76', 'bitboss' : 'BOSS', 
				'maker' : 'MKR', 'bikercoins' : 'BIC', 'cryptopennies' : 'CRPS', 'motocoin' : 'MOTO', 
				'neptuneclassic' : 'NTCC', 'numismatic collections' : 'XNC*', 'hexxcoin' : 'HXX', 'ghost coin' : 'SPKTR', 
				'machinecoin' : 'MAC', 'selencoin' : 'SEL', 'noocoin' : 'NOO', '23 skidoo' : 'CHAO', 
				'goldenbird' : 'XGB', 'yamahacoin' : 'YMC', 'jokercoin' : 'JOK', 'gravitybit' : 'GBIT', 
				'tecoin' : 'TEC', 'bombcoin' : 'BOMB', 'ride my car' : 'RIDE', 'private instant verified transaction' : 'PIVX', 
				'klingon empire darsek' : 'KED', 'coino' : 'CNO', 'wealthcoin' : 'WEALTH', 'internet of people' : 'IOP', 
				'spectre' : 'XSPEC', 'pepe cash' : 'PEPECASH', 'clickcoin' : 'CLICK', 'elysium' : 'ELS', 
				'kushcoin' : 'KUSH', 'eryllium' : 'ERY', 'pluton' : 'PLU', 'president trump' : 'PRES', 
				'bitzcoin' : 'BTZ', 'opes' : 'OPES', 'waves community token' : 'WCT', 'ubiq' : 'UBQ', 
				'ratio' : 'RATIO', 'babes and nerds' : 'BAN', 'nicecoin' : 'NICE', 'smurfcoin' : 'SMF', 
				'cryptoworldxtoken' : 'CWXT', 'techcoin' : 'TECH', 'circuitcoin' : 'CIR', 'lepencoin' : 'LEPEN', 
				'roundcoin' : 'ROUND', 'marijuanacoin' : 'MAR', 'marxcoin' : 'MARX', 'tatiana coin' : 'TAT', 
				'hazecoin' : 'HAZE', 'printerium' : 'PRX', 'neurocoin' : 'NRC', 'paccoin' : 'PAC', 
				'impeach' : 'IMPCH', 'errorcoin' : 'ERR', 'trueinvestmentcoin' : 'TIC', 'nukecoin' : 'NUKE', 
				'everyonescoin' : 'EOC', 'solarflarecoin' : 'SFC', 'janecoin' : 'JANE', 'paranoiacoin' : 'PARA', 
				'mastermint' : 'MM', 'bitcedi' : 'BXC', 'ninjadoge' : 'NDOGE', 'zilbercoin' : 'ZBC', 
				'melon' : 'MLN', 'tenx' : 'PAY', 'orocoin' : 'ORO', 'trashburn' : 'TBCX', 
				'mastercar' : 'MCAR', 'techshares' : 'THS', 'united arab emirates coin' : 'UAEC', 'eaglecoin' : 'EA', 
				'persistent information exchange' : 'PIE', 'creativechain' : 'CREA', 'wisdomcoin' : 'WISC', 'beavercoin' : 'BVC', 
				'findcoin' : 'FIND', 'melite' : 'MLITE', 'stalincoin' : 'STALIN', 'tattoocoin' : 'TSE', 
				'vaultcoin' : 'VLTC', 'biobar' : 'BIOB', 'swarm city token' : 'SWT', 'pascal lite' : 'PASL', 
				'zero' : 'ZER', 'chatcoin' : 'CHAT', 'trollplay' : 'TPAY', 'netko' : 'NETKO', 
				'zoin' : 'ZOI', 'honey' : 'HONEY', 'martexcoin' : 'MXT', 'musicoin' : 'MUSIC', 
				'databits' : 'DTB', 'bitvegan' : 'VEG', 'mbitbooks' : 'MBIT', 'bitvolt' : 'VOLT', 
				'mobilego' : 'MGO', 'edgeless' : 'EDG', 'bankcoin' : 'B@', 'bestchain' : 'BEST', 
				'chaincoin' : 'CHC', 'zennies' : 'ZENI', 'planetcoin' : 'PLANET', 'duckduckcoin' : 'DUCK', 
				'bnrtxcoin' : 'BNX', 'battlestake' : 'BSTK', 'renoscoin' : 'RNS', 'amis' : 'AMIS', 
				'kayı' : 'KAYI', 'virtacoinplus' : 'XVP', 'doubloon' : 'BOAT', 'tajcoin' : 'TAJ', 
				'impact' : 'IMX', 'cryptojournal' : 'CJC', 'amygws' : 'AMY', 'cubits' : 'QBT', 
				'starcredits' : 'SRC*', 'eb3coin' : 'EB3', 'the vegan initiative' : 'XVE', 'fazzcoin' : 'FAZZ', 
				'aptcoin' : 'APT', 'blazercoin' : 'BLAZR', 'arpacoin' : 'ARPA', 'boats and bitches' : 'BNB*', 
				'universe' : 'UNI', 'ecocoin' : 'ECO', 'solaris' : 'XLR', 'dark' : 'DARK', 
				'donationcoin' : 'DON', 'mercury' : 'MER', 'wavesgo' : 'WGO', 'iex.ec' : 'RLC', 
				'atmos' : 'ATMS', 'inpay' : 'INPAY', 'encryptotel' : 'ETT', 'wbtc' : 'WBTC', 
				'visio' : 'VISIO', 'happycoin' : 'HPC', 'giotto coin' : 'GOT', 'coinonat' : 'CXT', 
				'emporiumcoin' : 'EMPC', 'gnosis' : 'GNO', 'legends cryptocurrency' : 'LGD', 'token as a service' : 'TAAS', 
				'swagbucks' : 'BUCKS', 'xtrabytes' : 'XBY', 'guppy' : 'GUP', 'macroncoin' : 'MCRN', 
				'lunyr' : 'LUN', 'condensate' : 'RAIN', 'wearesatoshi' : 'WSX', 'ivugeoevolutioncoin' : 'IEC', 
				'independent money system' : 'IMS', 'arguscoin' : 'ARGUS', 'centurion' : 'CNT', 'lomocoin' : 'LMC', 
				'tokencard  ' : 'TKN', 'bitcoin scrypt' : 'BTCS', 'procurrency' : 'PROC', 'goldreserve' : 'XGR', 
				'warcoin' : 'WRC*', 'benjirolls' : 'BENJI', 'humaniq' : 'HMQ', 'blockchain capital' : 'BCAP', 
				'parallelcoin' : 'DUO', 'riptobux' : 'RBX', 'growthcoin' : 'GRW', 'apx' : 'APX', 
				'milocoin' : 'MILO', 'oldv' : 'OLV', 'ilcoin' : 'ILC', 'minersreward' : 'MRT', 
				'iou1' : 'IOU', 'prizm' : 'PZM', 'phreak' : 'PHR', 'aragon' : 'ANT', 
				'pupacoin' : 'PUPA', 'ricecoin' : 'RICE', 'c-bits' : 'XCT', 'degas coin' : 'DEA', 
				'coinmatic' : 'CTIC', 'tappingcoin' : 'TAP', 'bitokx' : 'BITOK', 'primalbase' : 'PBT', 
				'milkcoin' : 'MUU', 'infinium-8' : 'INF8', 'html coin' : 'HTML5', 'minereum' : 'MNE', 
				'etheroll' : 'DICE', 'subscriptio' : 'SUB*', 'ultimate secure cash' : 'USC', 'duxcoin' : 'DUX', 
				'poisonivycoin' : 'XPS', 'equitrader' : 'EQT', 'insane coin' : 'INSN', 'basic attention token' : 'BAT', 
				'manet coin' : 'MAT*', 'f16coin' : 'F16', 'hamstercoin' : 'HAMS', 'qtum' : 'QTUM', 
				'nefariouscoin' : 'NEF', 'zencash' : 'ZEN', 'boscoin' : 'BOS', 'qwark' : 'QWARK', 
				'iota' : 'IOT', 'quantum resistant ledger' : 'QRL', 'adelphoi' : 'ADL', 'e-currencycoin' : 'ECC', 
				'patientory' : 'PTOY', 'zrcoin' : 'ZRC', 'lykke' : 'LKK', 'espers' : 'ESP', 
				'satoshimadness' : 'MAD', 'dynamic' : 'DYN', 'sequence' : 'SEQ', 'mcap' : 'MCAP', 
				'mysterium' : 'MYST', 'veritaseum' : 'VERI', 'sonm' : 'SNM', 'skycoin' : 'SKY', 
				'cofound.it' : 'CFI', 'status network token' : 'SNT', 'aventcoin' : 'AVT', 'civic' : 'CVC', 
				'ixledger' : 'IXT', 'dent' : 'DENT', 'ethos' : 'ETHOS', 'starta' : 'STA', 
				'true flip lottery' : 'TFL', 'ergo' : 'EFYT', 'tezos' : 'XTZ', 'numerai' : 'NMR', 
				'adex' : 'ADX', 'quantum' : 'QAU', 'ecobit' : 'ECOB', 'polybius' : 'PLBT', 
				'tether' : 'USDT', 'raiblocks' : 'XRB', 'ahoolee' : 'AHT', 'atb coin' : 'ATB', 
				'blocktix' : 'TIX', 'chancoin' : '4CHN', 'compcoin' : 'CMP', 'rivetz' : 'RVT', 
				'harbour dao' : 'HRB', 'nimiq exchange token' : 'NET*', '8 circuit studios' : '8BT', 'coindash' : 'CDT', 
				'act' : 'ACT', 'district0x' : 'DNT', 'suretly' : 'SUR', 'cryptoping' : 'PING', 
				'makeitviral' : 'MIV', 'dao.casino' : 'BET*', 'santiment' : 'SAN', 'kin' : 'KIN', 
				'wagerr' : 'WGR', 'elastic' : 'XEL', 'nvo' : 'NVST', 'funfair' : 'FUN', 
				'funcoin' : 'FUNC', 'paquarium' : 'PQT', 'giga watt' : 'WTT', 'metal' : 'MTL', 
				'hive' : 'HVN', 'mybit' : 'MYB', 'populous' : 'PPT', 'suncontract' : 'SNC', 
				'starbase' : 'STAR', 'corion' : 'COR', 'rialto.ai' : 'XRL', 'orocrypt' : 'OROC', 
				'openanx' : 'OAX', 'monster byte inc' : 'MBI', 'digital developers fund' : 'DDF', 'dimcoin' : 'DIM', 
				'gilgam' : 'GGS', 'encrypgen' : 'DNA', 'fundyourselfnow' : 'FYN', 'fundrequest' : 'FND', 
				'dinastycoin' : 'DCY', 'cryptoforecast' : 'CFT', 'denarius' : 'DNR', 'digitalprice' : 'DP', 
				'virta unique coin' : 'VUC', 'bitcoin planet' : 'BTPL', 'unify' : 'UNIFY', 'imperialcoin' : 'IPC', 
				'britcoin' : 'BRIT', 'ammo rewards' : 'AMMO', 'socialcoin' : 'SOCC', 'mass.cloud' : 'MASS', 
				'latoken' : 'LA', 'immla' : 'IML', 'exchange union' : 'XUC', 'bitjob' : 'STU', 
				'pillar' : 'PLR', 'geofunders' : 'GUNS', 'investfeed' : 'IFT', 'bitclave' : 'CAT*', 
				'propy' : 'PRO', 'synchrocoin' : 'SYC', 'indorse' : 'IND', 'bowhead health' : 'AHT*', 
				'tribetoken' : 'TRIBE', '0x' : 'ZRX', 'tierion' : 'TNT', 'presearch' : 'PRE*', 
				'coss' : 'COSS', 'napoleon x' : 'NPX', 'storj' : 'STORJ', 'scorecoin' : 'SCORE', 
				'omisego' : 'OMG', 'octanox' : 'OTX', 'equibit' : 'EQB', 'voise' : 'VOISE', 
				'ethbits' : 'ETBS', 'crypviser' : 'CVCOIN', 'dcorp' : 'DRP', 'arcticcoin' : 'ARC', 
				'bogcoin' : 'BOG', 'neverdie' : 'NDC', 'po.et' : 'POE', 'adtoken' : 'ADT', 
				'aeternity' : 'AE', 'useless ethereum token' : 'UET', 'particl' : 'PART', 'agoras token' : 'AGRS', 
				'beachcoin' : 'SAND', 'aicoin' : 'XAI*', 'dmarket' : 'DMT', 'das' : 'DAS', 
				'blockcat' : 'CAT', 'coinjob' : 'XCJ', 'royal kingdom coin' : 'RKC', 'linda' : 'LINDA', 
				'spoon' : 'SPN', 'king93' : 'KING', 'anacrypt' : 'ANCP', 'reality clash' : 'RCC', 
				'rootproject' : 'ROOTS', 'sosnovkino' : 'SNK', 'cryptoabs' : 'CABS', 'opus' : 'OPT', 
				'openzen' : 'ZNT', 'bits digit' : 'BITSD', 'leviarcoin' : 'XLC', 'skincoin' : 'SKIN', 
				'mothership' : 'MSP', 'hirematch' : 'HIRE', 'brickblock' : 'BBT*', 'real' : 'REAL', 
				'dentalfix' : 'DFBT', 'equi' : 'EQ', 'wolk' : 'WOLK', 'viberate' : 'VIB', 
				'deeponion' : 'ONION', 'bitcore' : 'BTX', 'idice' : 'ICE', 'sphre air' : 'XID', 
				'gcoin' : 'GCN', 'cosmos' : 'ATOM*', 'decentraland' : 'MANA', 'ico openledger' : 'ICOO', 
				'timereum' : 'TME', 'smartcash' : 'SMART', 'signatum' : 'SIGT', 'onix' : 'ONX', 
				'coeval' : 'COE', 'arena' : 'ARENA', 'wink' : 'WINK', 'cream' : 'CRM', 
				'bitcoin cash' : 'BCH', 'digipulse' : 'DGPT', 'mobius' : 'MOBI', 'bitdice' : 'CSNO', 
				'kickcoin' : 'KICK', 'solar dao' : 'SDAO', 'stox' : 'STX', 'binance coin' : 'BNB', 
				'core group asset' : 'CORE', 'kencoin' : 'KCN', 'qvolta' : 'QVT', 'ties network' : 'TIE', 
				'autoria' : 'AUT', 'codetract' : 'CTT', 'monkey' : 'MNY', 'monetha' : 'MTH', 
				'cccoin' : 'CCC', 'umbrella coin' : 'UMC', 'bitmxittz' : 'BMXT', 'gas' : 'GAS', 
				'filecoin' : 'FIL', 'oceanlab' : 'OCL', 'benjacoin' : 'BNC', 'tomahawkcoin' : 'TOM', 
				'bytom' : 'BTM*', 'asch' : 'XAS', 'smnx' : 'SMNX', 'dentacoin' : 'DCN', 
				'agrello delta' : 'DLT', 'macroverse' : 'MRV', 'embers' : 'MBRS', 'substratum network' : 'SUB', 
				'memessenger' : 'MET', 'neblio' : 'NEBL', 'prospectors' : 'PGL', 'monacocoin' : 'XMCC', 
				'cash poker pro' : 'CASH*', 'campuscoin' : 'CMPCO', 'detectortoken' : 'DTCT', 'centra' : 'CTR', 
				'wavesnode.net' : 'WNET', 'paragon' : 'PRG', 'thankyou' : 'THNX', 'healthyworm' : 'WORM', 
				'fuck token' : 'FUCK', 'veredictum' : 'VNT', 'smart investment fund token' : 'SIFT', 'ignis' : 'IGNIS', 
				'iwtoken' : 'IWT', 'justdatingsite' : 'JDC', 'intelligent trading technologies' : 'ITT', 'everex' : 'EVX', 
				'icobox' : 'ICOS', 'lampix' : 'PIX', 'medibond' : 'MEDI', 'hello gold' : 'HGT', 
				'litra' : 'LTA', 'nimfamoney' : 'NIMFA', 'scorista' : 'SCOR', 'cprop' : 'MLS', 
				'kexcoin' : 'KEX', 'cobinhood' : 'COB', 'bitradio' : 'BRO', 'minex' : 'MINEX', 
				'atlant' : 'ATL', 'becksang' : 'ARI*', 'magos' : 'MAG*', 'draftcoin' : 'DFT', 
				'vechain' : 'VEN', 'utrust' : 'UTK', 'latium' : 'LAT', 'sojourn coin' : 'SOJ', 
				'hedge token' : 'HDG', 'stakecoin' : 'STCN', 'sqpay' : 'SQP', 'etheriya' : 'RIYA', 
				'ethereum.link' : 'LNK', 'ambrosus' : 'AMB', 'wanchain' : 'WAN', 'goldmint' : 'MNT', 
				'altocar' : 'ALTOCAR', 'credo' : 'CFT*', 'blockchain index' : 'BLX', 'boulle' : 'BOU', 
				'oxycoin' : 'OXY', 'tap project' : 'TTT', 'acumen' : 'AMT', 'gimli' : 'GIM', 
				'newyorkcoin' : 'NYC', 'frazcoin' : 'FRAZ', 'easymine' : 'EMT', 'gx coin' : 'GXC', 
				'hubiit' : 'HBT', 'kronecoin' : 'KRONE', 'scrypto' : 'SRT', 'avalon' : 'AVA', 
				'buildteam' : 'BT', 'adcoin' : 'ACC', 'ar.cash' : 'AR*', 'z2 coin' : 'Z2', 
				'linx' : 'LINX', 'coinonatx' : 'XCXT', 'blakestar' : 'BLAS', 'goodcoin' : 'GOOD', 
				'social nexus' : 'SCL', 'travel coin' : 'TRV', 'cryptum' : 'CRTM', 'exscudo' : 'EON', 
				'primas' : 'PST', 'matryx' : 'MTX', 'privatix' : 'PRIX', 'cartaxi' : 'CTX', 
				'enjin coin' : 'ENJ', 'cryptonex' : 'CNX', 'dropcoin' : 'DRC', 'etherparty' : 'FUEL', 
				'tokenstars' : 'ACE', 'worldcore' : 'WRC', 'waltonchain' : 'WTC', 'breakout stake' : 'BRX', 
				'wrtcoin' : 'WRT', 'ormeus coin' : 'ORME', 'deep gold' : 'DEEP', 'tothemoon' : 'TMT', 
				'crystal clear token ' : 'CCT', 'wish finance' : 'WSH', 'arna panacea' : 'ARNA', 'ab-chain' : 'ABC', 
				'papyrus' : 'PRP', 'blackmoon crypto' : 'BMC', 'skrilla token' : 'SKR*', '3des' : '3DES', 
				'paycentos' : 'PYN', 'kapu' : 'KAPU', 'sense token' : 'SENSE', 'cappasity' : 'CAPP', 
				'blockv' : 'VEE', 'facecoin' : 'FC', 'ripio' : 'RCN', 'doc.ai neuron' : 'NRN', 
				'eventchain' : 'EVC', 'chainlink' : 'LINK', 'eidoo' : 'EDO', 'a-token' : 'ATKN', 
				'kyber network' : 'KNC', 'rustbits' : 'RUSTBITS', 'rex' : 'REX', 'ethereum dark' : 'ETHD', 
				'sumokoin' : 'SUMO', 'elite 888' : '8S', 'hydrominer' : 'H2O', 'crypto tickets' : 'TKT', 
				'rhea' : 'RHEA', 'maecenas' : 'ART', 'domraider' : 'DRT', 'snovio' : 'SNOV', 
				'dreamteam token' : 'DTT', 'tracknettoken' : 'MTN', 'stockbet' : 'STOCKBET', 'algo.land' : 'PLM', 
				'foodcoin' : 'FDC', 'salt lending' : 'SALT', 'sandcoin' : 'SND', 'xp' : 'XP', 
				'loopring' : 'LRC', 'hshare' : 'HSR', 'zenome' : 'ZNA', 'ezmarket' : 'EZM', 
				'obsidian' : 'ODN', 'clearpoll' : 'POLL', 'moya token' : 'MTK', 'cashaa' : 'CAS', 
				'miniapps' : 'MAT', 'global jobcoin' : 'GJC', 'wi coin' : 'WIC', 'wandx' : 'WAND', 
				'elixir' : 'ELIX', 'ebitcoin' : 'EBTC', 'hackspace capital' : 'HAC', 'cardano' : 'ADA', 
				'yoyow' : 'YOYOW', 'regalcoin' : 'REC', 'opporty' : 'OPP', 'ice rock mining' : 'ROCK', 
				'earth token' : 'EARTH', 'icon project' : 'ICX', 'flash coin' : 'FLASH', 'graft network' : 'GRF', 
				'bitcoinz' : 'BTCZ', 'paypie' : 'PPP', 'peerguess' : 'GUESS', 'metaverse' : 'ETP', 
				'cryptonetix' : 'CIX', 'esports.com' : 'ERT', 'lakebanker' : 'BAC*', 'flik' : 'FLIK', 
				'trippki' : 'TRIP', 'multibot' : 'MBT', 'javvy' : 'JVY', 'alismedia' : 'ALIS', 
				'leverj' : 'LEV', 'arbi' : 'ARBI', 'eloplay' : 'ELT', 'request network' : 'REQ', 
				'aeron' : 'ARN', 'vibehub' : 'VIBE', 'rockchain' : 'ROK', 'x real estate development' : 'XRED', 
				'chronologic' : 'DAY', 'airswap' : 'AST', 'hextracoin' : 'HXT', 'cindicator' : 'CND', 
				'prosense.tv' : 'VRP', 'netm' : 'NTM', 'trezarcoin' : 'TZC', 'musiconomi' : 'MCI', 
				'worldwide asset exchange' : 'WAX', 'airtoken' : 'AIR', 'fujinto' : 'NTO', 'atc coin' : 'ATCC', 
				'kolion' : 'KOLION', 'wild crypto' : 'WILD', 'eltc' : 'ELTC2', 'ilcoin token' : 'ILCT', 
				'power ledger' : 'POWR', 'crypto20' : 'C20', 'anryze' : 'RYZ', 'genxcoin' : 'GXC*', 
				'elements' : 'ELM', 'terranovacoin' : 'TER', 'cybcsec coin' : 'XCS', 'bitqy' : 'BQ', 
				'clout' : 'CLOUT', 'propthereum' : 'PTC*', 'wabi' : 'WABI', 'everus' : 'EVR', 
				'toa coin' : 'TOA', 'monaize' : 'MNZ', 'vivo coin' : 'VIVO', 'red pulse' : 'RPX', 
				'moeda' : 'MDA', 'zeusshield' : 'ZSC', 'aureus' : 'AURS', 'change' : 'CAG', 
				'playkey' : 'PKT', 'e-chat' : 'ECHT', 'internxt' : 'INXT', 'authorship' : 'ATS', 
				'rg coin' : 'RGC', 'ethbet' : 'EBET', 'revain' : 'R', 'modum' : 'MOD', 
				'bitcomo' : 'BM*', 'cryptopay' : 'CPAY', 'rupee' : 'RUP', 'bonpay' : 'BON', 
				'whalecoin' : 'WHL', 'bitcoin gold' : 'BTG', 'uptoken' : 'UP', 'ethereum gold' : 'ETG', 
				'womencoin' : 'WOMEN', 'theresa may coin' : 'MAY', 'render token' : 'RNDR', 'eddie coin' : 'EDDIE', 
				'soma' : 'SCT*', 'namocoin' : 'NAMO', 'kucoin' : 'KCS', 'ethereum blue' : 'BLUE', 
				'follow coin' : 'FLLW', 'wyrify' : 'WYR', 'vezt' : 'VZT', 'indicoin' : 'INDI', 
				'luxcoin' : 'LUX', 'pirl' : 'PIRL', 'ethereum cash' : 'ECASH', 'wepower' : 'WPR', 
				'dragonchain' : 'DRGN', 'cybertrust' : 'CABS*', 'brat' : 'BRAT', 'dynamic trading rights' : 'DTR', 
				'cryptoinsight' : 'TKR', 'ethereumlite' : 'ELITE', 'xios' : 'XIOS', 'dovu' : 'DOVU', 
				'xenon' : 'XNN', 'bitcloud 2.0' : 'BTDX', 'lendoit' : 'LOAN', 'zabercoin' : 'ZAB', 
				'modulum' : 'MDL', 'bitfinex bitcoin future' : 'BT1', 'bitcoin segwit2x' : 'BT2', 'sharpe capital' : 'SHP', 
				'jincor' : 'JCR', 'extreme sportsbook' : 'XSB', 'eboost' : 'EBST', 'kekcoin' : 'KEK', 
				'aidcoin' : 'AID', 'blackholecoin' : 'BHC*', 'altcommunity coin' : 'ALTCOM', 'simpletoken' : 'OST', 
				'streamr datacoin' : 'DATA', 'ugchain' : 'UGT', 'datacoin' : 'DTC*', 'herocoin' : 'PLAY', 
				'pure' : 'PURE', 'cloud' : 'CLD', 'open trading network' : 'OTN', 'postoken' : 'POS', 
				'rebellious' : 'REBL', 'neo gold' : 'NEOG', 'exchangen' : 'EXN', 'tracto' : 'TRCT', 
				'unikoingold' : 'UKG', 'bitcoin red' : 'BTCRED', 'ebitcoincash' : 'EBCH', 'j coin' : 'JPC*', 
				'aix' : 'AXT', 'raiden network' : 'RDN*', 'rupaya' : 'RUPX', 'bluedragon' : 'BDR', 
				'dutch coin' : 'DUTCH', 'huncoin' : 'HNC*', 'madcoin' : 'MDC*', 'pura' : 'PURA', 
				'innova' : 'INN', 'decision token' : 'HST', 'blockmason credit protocol' : 'BCPT', 'bitdeal' : 'BDL', 
				'comsa' : 'CMS', 'billionaire token' : 'XBL', 'project zephyr' : 'ZEPH', 'atfs project' : 'ATFS', 
				'nuls' : 'NULS', 'phore' : 'PHR*', 'litecoincash' : 'LCASH', 'confido' : 'CFD', 
				'sophiatx' : 'SPHTX', 'wisercoin' : 'WSC', 'decent.bet' : 'DBET', 'go!' : 'XGOX', 
				'newbium' : 'NEWB', 'life' : 'LIFE', 'masari' : 'MSR', 'connectjob token' : 'CJT', 
				'ethersportcoin' : 'ESC', 'bankera' : 'BNK', 'ellaism' : 'ELLA', 'blockpool' : 'BPL', 
				'rocketcoin ' : 'ROCK*', 'droxne' : 'DRXNE', 'sakuracoin' : 'SKR', 'grid+' : 'GRID', 
				'platinumbar' : 'XPTX', 'genesis vision' : 'GVT', 'astronaut' : 'ASTRO', 'mercury protocol' : 'GMT', 
				'emphy' : 'EPY*', 'soarcoin' : 'SOAR', 'experty' : 'EXY', 'interstellar holdings' : 'HOLD', 
				'minexcoin' : 'MNX', 'viuly' : 'VIU', 'scorum' : 'SCR', 'düber' : 'DBR', 
				'advanced browsing token' : 'ABT', 'startercoin' : 'STC', 'quantstamp' : 'QSP', 'bitboost' : 'BBT', 
				'gobyte' : 'GBX', 'castle' : 'CSTL', 'quoine liquid' : 'QASH', 'kingn coin' : 'KNC**', 
				'triaconta' : 'TRIA', 'publica' : 'PBL', 'magnet' : 'MAG', 'stex' : 'STEX', 
				'upfiring' : 'UFR', 'lamden tau' : 'TAU', 'labrys' : 'LAB', 'flixxo' : 'FLIXX', 
				'farad' : 'FRD', 'payfair' : 'PFR', 'electra' : 'ECA', 'ludum token' : 'LDM', 
				'litecoin gold' : 'LTG', 'bitcoin diamond' : 'BCD', 'stashpay' : 'STP', 'spankchain' : 'SPANK', 
				'mywish' : 'WISH*', 'aerium' : 'AERM', 'plexcoin' : 'PLX', 'autonio' : 'NIO', 
				'etherbtc' : 'ETHB', 'commodity ad network' : 'CDX*', 'darico' : 'DARICO', 'votecoin' : 'VOT', 
				'uquid coin' : 'UQC', 'ethlend' : 'LEND', 'tio tour guides' : 'TIO*', 'shield' : 'XSH', 
				'bitcad' : 'BCD*', 'bridgecoin' : 'BCO', 'ong.social' : 'ONG', 'oyster pearl' : 'PRL', 
				'btcmoon' : 'BTCM', 'ethereum black' : 'ETBT', 'zcashgold' : 'ZCG', 'mutual coin' : 'MUT', 
				'aion' : 'AION', 'kittehcoin' : 'MEOW', 'divi' : 'DIVX', 'rchain' : 'RHOC', 
				' arcade city' : 'ARC*', 'rafl' : 'RFL', 'coinifi' : 'COFI', 'eltcoin' : 'ELTCOIN', 
				'gold reward token' : 'GRX', 'neurotoken' : 'NTK', 'eroscoin' : 'ERO', 'cybermiles' : 'CMT*', 
				'relex' : 'RLX', 'people' : 'MAN', 'cryptowave' : 'CWV', 'achain' : 'ACT*', 
				'neuro' : 'NRO', 'social send' : 'SEND', 'globaltoken' : 'GLT', 'x8currency' : 'X8X', 
				'bitcoal' : 'COAL', 'daxxcoin' : 'DAXX', 'bulwark' : 'BWK', 'monero gold' : 'XMRG', 
				'ethereumbitcoin' : 'BTCE', 'flypme' : 'FYP', 'boxycoin' : 'BOXY', 'nagacoin' : 'NGC', 
				'universa' : 'UTN', 'ethgas' : 'EGAS', 'digital assets power play' : 'DPP', 'targetcoin' : 'TGT', 
				'xinfin coin' : 'XDC', 'bmchain' : 'BMT', 'biocoin' : 'BIO', 'btc lite' : 'BTCL', 
				'peepcoin' : 'PCN', 'smartholdem' : 'STH', 'bitcoin revolution' : 'RBTC', 'verify' : 'CRED', 
				'super bitcoin' : 'SBTC', 'kalkulus' : 'KLK', 'ac3' : 'AC3', 'time new bank' : 'TNB', 
				'chips' : 'CHIPS', 'hacken' : 'HKN', 'b2b' : 'B2BX', 'lockchain' : 'LOC*', 
				'smartmesh' : 'SMT*', 'ethereumfog' : 'ETF', 'bitcoinx' : 'BCX*', 'straks' : 'STAK', 
				'neumark' : 'NEU', 'electroneum' : 'ETN', 'germancoin' : 'GER', 'digitalnote ' : 'XDN', 
				'fastcoin' : 'FST', 'bannercoin' : 'BCOIN', 'litecoin ultra' : 'LTCU', 'cannabiscoin' : 'CANN', 
				'salus' : 'SLS', 'bitair' : 'BTCA', 'intensecoin' : 'ITNS', 'gifto' : 'GTO', 
				'buzzcoin' : 'BUZZ', 'ins ecosystem' : 'INS', 'sirinlabs' : 'SRN', 'realisto' : 'REA', 
				'giftcoin' : 'GFT', 'galaxy esolutions' : 'GES', 'crowdcoinage' : 'CCOS', 'riptidecoin' : 'RIPT', 
				'luxmi coin' : 'LUX**', 'bounty0x' : 'BNTY', 'bread token' : 'BRD', 'canyacoin' : 'CAN', 
				'appcoins' : 'APPC', 'gladius' : 'GLA', 'jibrel network token' : 'JNT', 'media network coin' : 'MNT*', 
				'catcoin' : 'CAT1', 'bankex' : 'BKX', 'authoreon' : 'AUTH', 'coinvest' : 'COIN', 
				'odmcoin' : 'ODMC', 'adshares' : 'ADST', 'goldea' : 'GEA', 'infinity economics' : 'XIN', 
				'medibloc' : 'MED*', 'aelf' : 'ELF', 'social media market' : 'SMT', 'litebitcoin' : 'LBTC', 
				'flavorcoin' : 'FLVR', 'pepe' : 'MEME', 'bismuth' : 'BIS', 'alqo' : 'ALQO', 
				'growers international' : 'GRWI', 'edrcoin' : 'EDRC', 'karbowanec' : 'KRB', 'emercoin' : 'EMC', 
				'redcoin' : 'RED', 'insta cash coin' : 'ICC', 'alexandrite' : 'ALEX', 'zsecoin' : 'ZSE', 
				'vertcoin' : 'VTC', 'bitdegree' : 'BDG', 'locicoin' : 'LOCI', 'webcoin' : 'WEB', 
				'vsync' : 'VSX', 'cash & back coin' : 'CNBC', 'ultranote' : 'XUN', 'verge' : 'XVG', 
				'datum' : 'DAT', 'popularcoin' : 'POP', 'crowdcoin' : 'CRC*', 'phantomx' : 'PNX', 
				'bitasean' : 'BAS', 'deepbrain chain' : 'DBC', 'storm' : 'STORM', 'united traders token' : 'UTT', 
				'valorem' : 'VLR', 'crazy coin' : 'CZC', 'avesta' : 'AVE', 'covesting' : 'COV', 
				'adbank' : 'ADB', 'tronix' : 'TRX', 'davorcoin' : 'DAV', 'copico' : 'XCPO', 
				'guaranteed entrance token' : 'GET', 'index erc20' : 'ERC20', 'iot chain' : 'ITC', 'debitum token' : 'DEB', 
				'parkgene' : 'GENE', 'trade.io' : 'TIO', 'ucash' : 'XUC*', 'fintab' : 'FNT', 
				'envion' : 'EVN', 'crypto-x' : 'CWX', 'modultrade' : 'MTRC', 'gameflip' : 'FLP', 
				'crowdwiz' : 'WIZ', 'caviar' : 'CAV', 'selfkey' : 'KEY', 'tbis token' : 'BAR', 
				'sether' : 'SETH', 'data trading' : 'DTT*', 'hoqu' : 'HQX', 'eos' : 'EOS', 
				'energi token' : 'ETK', 'the abyss' : 'ABYSS', 'paypro' : 'PYP', 'gatcoin' : 'GAT', 
				'monaco' : 'MCO', 'numus' : 'NMS', 'photon' : 'PHO', 'desire' : 'DSR'}